In [5]:
from mlxtend.preprocessing import TransactionEncoder

In [6]:
dataset = [['Bedsheet','Cushion','Pillow','Cushion Cover','Pillow Cover'],
           ['Mattresses','Cushion','Pillow','Cushion Cover','Pillow Cover'],
           ['Bedsheet','Curtains','Cushion Cover','Pillow Cover'],
           ['Bedsheet','Mattresses','Blankets','Cushion Cover','Pillow Cover'],
           ['Blankets','Cushion','Cushion','Cushion Cover','Bath Towels'],
           ['Floor Coverings','Curtains','Mattresses','Pillow','Cushion'],
           ['Pillow Cover','Mattresses','Bedsheet','Cushion Cover','Blankets'],
           ['Floor Coverings','Cushion','Cushion Cover','Pillow','Bedsheet'],
           ['Mattresses','Blankets','Bath Towels','Pillow','Cushion'],
           ['Bedsheet','Blankets','Pillow Cover','Floor Coverings','Cushion Cover']]

In [7]:
te = TransactionEncoder()

In [8]:
data = te.fit(dataset).transform(dataset)

In [9]:
import pandas as pd

In [10]:
productdata = pd.DataFrame(data,columns = te.columns_)

In [11]:
productdata

,Bath Towels,Bedsheet,Blankets,Curtains,Cushion,Cushion Cover,Floor Coverings,Mattresses,Pillow,Pillow Cover
0,False,True,False,False,True,True,False,False,True,True
1,False,False,False,False,True,True,False,True,True,True
2,False,True,False,True,False,True,False,False,False,True
3,False,True,True,False,False,True,False,True,False,True
4,True,False,True,False,True,True,False,False,False,False
5,False,False,False,True,True,False,True,True,True,False
6,False,True,True,False,False,True,False,True,False,True
7,False,True,False,False,True,True,True,False,True,False
8,True,False,True,False,True,False,False,True,True,False
9,False,True,True,False,False,True,True,False,False,True

In [12]:
#Market basket analysis basically uses three diferent matrix
#1.Support 2. Confidence and 3. Lift.
#Support= It gives a fraction of records which contains factor the factor can be either one or multiple basically support tells us about the frequent combination of factors.

#Support = No of records per transactions containing factors (A,b or both ab)/No of total records.

#Confidence = No of records containing both a and b/No of records containing A.(Confidence tells us about how often factors a and b occur together given no of times A occurs)

#Eg - Suppose A is bread and B is butter the value of confidence will depict the number of records when bread and butter were together purchased/ When bread alone was purchased.

##Lift =It indicates the strength of the role over the random occurence of A and B . The greater the value of lift the more is the strength.
#If Lift is less than 1 it means that there is no association.

#If lift is equal to 1 this means that there is a very poor association.

#If lift is greater than 1 that means it is a good association.

#If lift is equal to 3 it means that if u buy A chances of buying B is three times .

#lift = Support of X union Y / Support of X * Support of Y

In [13]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

#Determining the frequent factors
frequent_factors = apriori(productdata,use_colnames=True,min_support=0.1,max_len=4)

#Filtering the factors on the basis of conditions
rules = association_rules(frequent_factors,metric ='lift',min_threshold=1)

#Displaying the first 10 records
print(rules.head(10).sort_values(by='confidence',ascending =False))

     antecedents    consequents  antecedent support  consequent support  \
1  (Bath Towels)     (Blankets)                 0.2                 0.5
3  (Bath Towels)      (Cushion)                 0.2                 0.6
8     (Blankets)     (Bedsheet)                 0.5                 0.6
5  (Bath Towels)   (Mattresses)                 0.2                 0.5
7  (Bath Towels)       (Pillow)                 0.2                 0.5
9     (Bedsheet)     (Blankets)                 0.6                 0.5
0     (Blankets)  (Bath Towels)                 0.5                 0.2
2      (Cushion)  (Bath Towels)                 0.6                 0.2
4   (Mattresses)  (Bath Towels)                 0.5                 0.2
6       (Pillow)  (Bath Towels)                 0.5                 0.2

   support  confidence      lift  leverage  conviction
1      0.2    1.000000  2.000000      0.10         inf
3      0.2    1.000000  1.666667      0.08         inf
8      0.3    0.600000  1.000000      0.00    1.000000
5      0.1    0.500000  1.000000      0.00    1.000000
7      0.1    0.500000  1.000000      0.00    1.000000
9      0.3    0.500000  1.000000      0.00    1.000000
0      0.2    0.400000  2.000000      0.10    1.333333
2      0.2    0.333333  1.666667      0.08    1.200000
4      0.1    0.200000  1.000000      0.00    1.000000
6      0.1    0.200000  1.000000      0.00    1.000000

In [14]:
#List the products which were sold min 50% times
apriori(productdata,use_colnames=True,min_support =0.5)

    support                                 itemsets
0       0.6                               (Bedsheet)
1       0.5                               (Blankets)
2       0.6                                (Cushion)
3       0.8                          (Cushion Cover)
4       0.5                             (Mattresses)
5       0.5                                 (Pillow)
6       0.6                           (Pillow Cover)
7       0.6                (Cushion Cover, Bedsheet)
8       0.5                 (Bedsheet, Pillow Cover)
9       0.5                        (Pillow, Cushion)
10      0.6            (Cushion Cover, Pillow Cover)
11      0.5  (Cushion Cover, Bedsheet, Pillow Cover)

In [15]:
#The data of the market basket analysis should be in the list format only.

In [16]:
frequent_itemsets = apriori(productdata,min_support=0.6,use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x:len(x))

In [26]:
frequent_itemsets[(frequent_itemsets['length']>=2) & (frequent_itemsets['support']>=0.5)]

   support                       itemsets  length
4      0.6      (Cushion Cover, Bedsheet)       2
5      0.6  (Cushion Cover, Pillow Cover)       2

In [28]:
frequent_itemsets[(frequent_itemsets['itemsets'] == {'Cushion Cover','Bedsheet'})]

   support                   itemsets  length
4      0.6  (Cushion Cover, Bedsheet)       2

In [34]:
target = '{\'Bedsheet\'}'

#Searching required strings in consequents and sorting values on confidence
results_Bedsheet = rules[rules['antecedents'].astype(str).str.contains(target,na =False)].sort_values(by='confidence',ascending =False)

#Displaying first 10 records
results_Bedsheet.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
11,(Bedsheet),(Cushion Cover),0.6,0.8,0.6,1.000000,1.250000,0.12,inf
146,(Bedsheet),"(Cushion Cover, Pillow Cover)",0.6,0.6,0.5,0.833333,1.388889,0.14,2.40
14,(Bedsheet),(Pillow Cover),0.6,0.6,0.5,0.833333,1.388889,0.14,2.40
108,(Bedsheet),"(Blankets, Pillow Cover)",0.6,0.3,0.3,0.500000,1.666667,0.12,1.40
394,(Bedsheet),"(Cushion Cover, Blankets, Pillow Cover)",0.6,0.3,0.3,0.500000,1.666667,0.12,1.40
9,(Bedsheet),(Blankets),0.6,0.5,0.3,0.500000,1.000000,0.00,1.00
91,(Bedsheet),"(Cushion Cover, Blankets)",0.6,0.4,0.3,0.500000,1.250000,0.06,1.20
102,(Bedsheet),"(Blankets, Mattresses)",0.6,0.3,0.2,0.333333,1.111111,0.02,1.05
458,(Bedsheet),"(Pillow, Cushion, Cushion Cover)",0.6,0.3,0.2,0.333333,1.111111,0.02,1.05
422,(Bedsheet),"(Blankets, Mattresses, Pillow Cover)",0.6,0.2,0.2,0.333333,1.666667,0.08,1.20

In [ ]:
#If someone buys bedsheet , there is probability that he can also buy pillow cover and cushion cover.
#So the owner of the super store should do the market basket analysis for frequent pattern generation of items.